### PR TITLE
Fix applications count in workshop card

### LINKED ISSUE #1327: [Workshop] The number of applications is incorrect in the workshop card.
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/#/
2. Log in as Parent
3. Submit an application for a child to the workshop.
4. Delete the child for whom the application was submitted.

**Steps to reproduce**
1. Log in as a service provider of the workshop to which the application was submitted.
2. Go to "Заявки" on the top right corner drop down list.
3. Pay attention to the number of applications with the status "Очікує підтвердження"
4. Go to "Мої гуртки" tab.
5. Pay attention to the card of the workshop for which the application was submitted, to the line "Очікує підтвердження".

**Actual result**
The information in the workshop card about the number of applications with the status "Очікує підтвердження" does not change after the removal of the child who submitted the application.
image

image

**Expected result**
The information in the workshop card changes dynamically with any changes in the applications. If the child who applied for the workshop is deleted, then this application is removed from the list of applications and, accordingly, the number of applications with the status "Очікує підтвердження" changes in the corresponding workshop card.

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: medium"), Type  "API" (for back-end bugs).

### PR DESCRIPTION
**Pull request by VitaliyYuras**

### CODE REVIEW

File: OutOfSchool/OutOfSchool.DataAccess/Repository/ApplicationRepository.cs [hunk 1]
```diff
@@ -83,4 +84,17 @@ public async Task<int> UpdateAllApprovedApplications()
                 (int)ApplicationStatus.Approved)
             .ConfigureAwait(false);
     }
+
+    public async Task DeleteChildApplications(Guid childId)
+    {
+        List<Application> applicationsToDelete = await dbContext.Applications
+        .Where(app => app.ChildId == childId)
+        .ToListAsync();
```
Comment (VadymLevkovskyi) [inline OutOfSchool/OutOfSchool.DataAccess/Repository/ApplicationRepository.cs]: (Code style) Please fix code indentation.

**Review by VadymLevkovskyi — COMMENTED** [review]
I see two major changes in code - adding deletion of child applications and changed `WorkshopProviderViewCard.AmountOfPendingApplications` mapping profile. 
Could they both be tested? Could other uncovered lines be tested as well? 

Also, please see minor code formatting issue in separate comment.

**Comment by VitaliyYuras** [comment]
> I see two major changes in code - adding deletion of child applications and changed `WorkshopProviderViewCard.AmountOfPendingApplications` mapping profile. Could they both be tested? Could other uncovered lines be tested as well?
> 
> Also, please see minor code formatting issue in separate comment.

Fixed

**Review by VadymLevkovskyi — APPROVED** [review]
